use std::path::PathBuf;
use std::process::Command;
use cluaizd_errors::StorageError;

/// Compiles a raw Rust code string into a `.wasm` file using Cargo in the background.
/// The resulting `.wasm` file is written directly to `active_dnas/`.
pub fn compile_rust_to_wasm(name: &str, rust_code: &str) -> Result<(), StorageError> {
    // We will use a temporary directory to build the WASM file
    let tmp_dir = std::env::temp_dir().join(format!("cluaizd_auto_wasm_{}", name));
    
    // Create or clear the tmp dir
    if tmp_dir.exists() {
        let _ = std::fs::remove_dir_all(&tmp_dir);
    }
    std::fs::create_dir_all(&tmp_dir)
        .map_err(|e| StorageError::WasmExecutionFailed(format!("Failed to create temp dir: {}", e)))?;

    // 1. Initialize a new Cargo lib project
    let status = Command::new("cargo")
        .arg("init")
        .arg("--lib")
        .arg(&tmp_dir)
        .status()
        .map_err(|e| StorageError::WasmExecutionFailed(format!("Failed to run cargo init: {}", e)))?;

    if !status.success() {
        return Err(StorageError::WasmExecutionFailed("cargo init failed".to_string()));
    }

    // 2. Overwrite Cargo.toml to compile as cdylib (WASM compatible)
    let cargo_toml_path = tmp_dir.join("Cargo.toml");
    let cargo_toml_content = format!(
        r#"[package]
name = "{}"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
"#,
        name
    );
    std::fs::write(&cargo_toml_path, cargo_toml_content)
        .map_err(|e| StorageError::WasmExecutionFailed(format!("Failed to write Cargo.toml: {}", e)))?;

    // 3. Overwrite src/lib.rs with the provided Rust code
    let lib_rs_path = tmp_dir.join("src").join("lib.rs");
    std::fs::write(&lib_rs_path, rust_code)
        .map_err(|e| StorageError::WasmExecutionFailed(format!("Failed to write src/lib.rs: {}", e)))?;

    // 4. Build the project using `wasm32-unknown-unknown`
    tracing::info!("🧬 Auto-WASM: Compiling '{}' to wasm32...", name);
    let build_status = Command::new("cargo")
        .arg("build")
        .arg("--target")
        .arg("wasm32-unknown-unknown")
        .arg("--release")
        .current_dir(&tmp_dir)
        .status()
        .map_err(|e| StorageError::WasmExecutionFailed(format!("Failed to run cargo build: {}", e)))?;

    if !build_status.success() {
        return Err(StorageError::WasmExecutionFailed(format!("Compilation of '{}' failed. Check syntax.", name)));
    }

    // 5. Copy the output .wasm file to active_dnas/
    let wasm_file_name = format!("{}.wasm", name.replace("-", "_"));
    let target_wasm = tmp_dir
        .join("target")
        .join("wasm32-unknown-unknown")
        .join("release")
        .join(&wasm_file_name);

    if !target_wasm.exists() {
        return Err(StorageError::WasmExecutionFailed("WASM file was not generated by rustc".to_string()));
    }

    let active_dnas_dir = PathBuf::from("active_dnas");
    if !active_dnas_dir.exists() {
        std::fs::create_dir_all(&active_dnas_dir).unwrap_or_default();
    }
    
    let final_dest = active_dnas_dir.join(format!("{}.wasm", name));
    std::fs::copy(&target_wasm, &final_dest)
        .map_err(|e| StorageError::WasmExecutionFailed(format!("Failed to copy WASM to active_dnas: {}", e)))?;

    // 6. Cleanup
    let _ = std::fs::remove_dir_all(&tmp_dir);

    tracing::info!("🧬 Auto-WASM: Successfully built and hot-reloaded '{}'!", name);
    Ok(())
}
