use std::fs::OpenOptions;
use std::io::Write;
use std::time::SystemTime;

pub struct TestLogger {
    test_name: String,
    start_time: SystemTime,
}

impl TestLogger {
    pub fn start(name: &str) -> Self {
        Self {
            test_name: name.to_string(),
            start_time: SystemTime::now(),
        }
    }

    pub fn pass(&self, details: &str) {
        self.log_result("✅ PASS", details);
    }

    pub fn fail(&self, error: &str) {
        self.log_result("❌ FAIL", error);
    }

    fn log_result(&self, status: &str, details: &str) {
        let duration = self.start_time.elapsed().unwrap_or_default();
        let timestamp = chrono::Local::now().format("%Y-%m-%d %H:%M:%S");

        let log_entry = format!(
            "| {} | **{}** | {} | {:.2}ms | {} |\n",
            timestamp, self.test_name, status, duration.as_secs_f64() * 1000.0, details
        );

        // Ensure the file exists and has a header if it's new
        let file_path = "test_result.md";
        let is_new = !std::path::Path::new(file_path).exists();

        let mut file = OpenOptions::new()
            .create(true)
            .append(true)
            .open(file_path)
            .expect("Failed to open test_result.md");

        if is_new {
            writeln!(file, "# 🧪 Cluaizd Deep Test Results").unwrap();
            writeln!(file, "This file is auto-generated by the custom TestLogger to track ACID and Performance tests.\n").unwrap();
            writeln!(file, "| Timestamp | Test Name | Status | Duration | Details |").unwrap();
            writeln!(file, "|-----------|-----------|--------|----------|---------|").unwrap();
        }

        file.write_all(log_entry.as_bytes()).unwrap();
        
        // Also print to console for cargo test output
        println!("[{}] {} ({}ms): {}", status, self.test_name, duration.as_secs_f64() * 1000.0, details);
    }
}
